name: yash_project
description: "A Flutter project like Myntra (Nike Clone)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Utils
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  shared_preferences: ^2.3.3
  carousel_slider: ^5.1.1
  lottie: ^3.1.2

  # Firebase
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11

  # Media
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/puma/
    - assets/addidas/
    - assets/sportshoes/
    - assets/jordan/
    - assets/nike/
    - assets/woman/
    - assets/Nikes/
    - assets/shop/